In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_excel('Detalle precios y productos fabricados 2022.xlsx')
df

,CVE_DOC,FECHA_DOC,NOMBRE_VENDEDOR,NOMBRE_CLIENTE,CANT,CVE_ART,DESCR,PRECIO_UNITARIO,COSTO_UNITARIO,COSTO_UNITARIO_CALCULADO,SUBTOTAL_PARTIDA,COSTO_TOTAL_CALCULADO,MARGEN_UNITARIO_CALCULADO,MARGEN_TOTAL_CALCULADO
0,F37034,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,1,TUE00244,"TUB COBRE 5/16""ØX165MM CIRCULA1.5KW127V",434.48,52.80,52.80,434.48,52.80,381.68,381.68
1,F37036,2022-01-05,LETICIA RAMIREZ HERNANDEZ,JUAN ANTONIO RESENDIZ UGALDE,1,TUA00028,"TUA U"" 5/16 ØX250MM 1200W 120V TAP1""NPT",1264.05,327.18,327.18,1264.05,327.18,936.87,936.87
2,F37041,2022-01-05,DIEGO ARMANDO LEON DURAN,ANA BARBARA CRUZ PALACIOS,7,TP0007,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT,551.61,177.68,177.68,3861.29,1243.73,373.94,2617.56
3,F37042,2022-01-05,DIEGO ARMANDO LEON DURAN,OMAR RODRIGUEZ GOMEZ,1,TP0001,TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT,140.00,38.96,38.96,140.00,38.96,101.04,101.04
4,F37043,2022-01-05,LETICIA RAMIREZ HERNANDEZ,PÚBLICO EN GENERAL,2,BP00242,BAN P INOX 115MMX235MM 1000W 127V T/TOR,172.41,101.71,101.71,344.83,203.42,70.71,141.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1421,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12F1040A00,"CAS INOX 1/2""ØX3"" 400W 127V EXT.30CM",712.00,102.31,102.31,4272.00,613.88,609.69,3658.12
1422,F39834,2022-12-23,LETICIA RAMIREZ HERNANDEZ,LUIS ENRIQUE PATIÑO PEREZ,6,CS12H1050A00,"CAS INOX 1/2""ØX4"" 500W 127V EXT30CM",718.60,104.69,104.69,4311.60,628.12,613.91,3683.48
1423,F39835,2022-12-23,LETICIA RAMIREZ HERNANDEZ,SEVEN DAYS ALL SPORT,3,TUE00394,"TUB INOX 5/16""ØX300MM 5300W 220V ""M"" ESP",2182.35,0.00,596.55,6547.05,1789.64,1585.80,4757.41
1424,F39837,2022-12-23,LETICIA RAMIREZ HERNANDEZ,REVUELTA MONTECARLO,1,TUA00470,"TUB INOX 1/2""ØX500MM 10KW 220V 2 1/2""NPT",5909.84,1884.35,1884.35,5909.84,1884.35,4025.49,4025.49
1425,F39838,2022-12-23,AARON NUÑO CORDOVA,CPEG SOLUTIONS,10,RB00007,FAB BOBINA DSD1 6 COLOCAR B/NUEVA 488V,1406.00,0.00,80.66,14060.00,806.55,1325.34,13253.45

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1426 entries, 0 to 1425
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   CVE_DOC                    1426 non-null   object
 1   FECHA_DOC                  1426 non-null   datetime64[ns]
 2   NOMBRE_VENDEDOR            1424 non-null   object
 3   NOMBRE_CLIENTE             1426 non-null   object
 4   CANT                       1426 non-null   int64
 5   CVE_ART                    1426 non-null   object
 6   DESCR                      1426 non-null   object
 7   PRECIO_UNITARIO            1426 non-null   float64
 8   COSTO_UNITARIO             1426 non-null   float64
 9   COSTO_UNITARIO_CALCULADO   1426 non-null   float64
 10  SUBTOTAL_PARTIDA           1426 non-null   float64
 11  COSTO_TOTAL_CALCULADO      1426 non-null   float64
 12  MARGEN_UNITARIO_CALCULADO  1426 non-null   float64
 13  MARGEN_TOTAL_CALCULADO     1426 non-null   float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 156.1+ KB

*Filtros basicos para variables cualitativas*

In [26]:
# 1.- Filtro por cliente específico
filtro_cliente = df[df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL"]
filtro_cliente.to_csv("filtro_cliente.csv")
print(filtro_cliente.head())

   CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR      NOMBRE_CLIENTE  CANT  \
0   F37034 2022-01-05  LETICIA RAMIREZ HERNANDEZ  PÚBLICO EN GENERAL     1
4   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ  PÚBLICO EN GENERAL     2
5   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ  PÚBLICO EN GENERAL     2
57  F37134 2022-01-17  LETICIA RAMIREZ HERNANDEZ  PÚBLICO EN GENERAL     4
69  F37153 2022-01-20  LETICIA RAMIREZ HERNANDEZ  PÚBLICO EN GENERAL     2

     CVE_ART                                    DESCR  PRECIO_UNITARIO  \
0   TUE00244  TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V           434.48
4    BP00242  BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41
5    BP00243    BAN P INOX 55MMX235MM 450W 127V T/TOR           237.07
57   RB00010  BOB 8020 CAL.19 1612W 127V CER-8CANALES           605.00
69   BP00245    BAN P COMUN 100CMX21MM 900W220V T/TOR           522.00

    COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
0            52.80                     52.80            434.48
4           101.71                    101.71            344.83
5            49.41                     49.41            474.14
57           44.70                     44.70           2420.00
69           51.38                     51.38           1044.00

    COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
0                   52.80                     381.68                  381.68
4                  203.42                      70.71                  141.41
5                   98.82                     187.66                  375.32
57                 178.80                     560.30                 2241.20
69                 102.76                     470.62                  941.24

In [27]:
# 2.- Filtro por filas específicas

# Variación 1: Filtrar filas de la 3 a la 10
filtro_filas_var1 = df.iloc[3:11, :]
filtro_filas_var1.to_csv("filtro_filas_var1.csv", index=False)
print(filtro_filas_var1)

# Variación 2: Filtrar filas 1, 4 y 7
filtro_filas_var2 = df.iloc[[1, 4, 7], :]
filtro_filas_var2.to_csv("filtro_filas_var2.csv", index=False)
print(filtro_filas_var2)

   CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR  \
3   F37042 2022-01-05   DIEGO ARMANDO LEON DURAN
4   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
5   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
6   F37044 2022-01-05   DIEGO ARMANDO LEON DURAN
7   F37046 2022-01-05  LETICIA RAMIREZ HERNANDEZ
8   F37048 2022-01-05   DIEGO ARMANDO LEON DURAN
9   F37049 2022-01-05   DIEGO ARMANDO LEON DURAN
10  F37050 2022-01-05   DIEGO ARMANDO LEON DURAN

                         NOMBRE_CLIENTE  CANT   CVE_ART  \
3                  OMAR RODRIGUEZ GOMEZ     1    TP0001
4                    PÚBLICO EN GENERAL     2   BP00242
5                    PÚBLICO EN GENERAL     2   BP00243
6   AIRBUS HELICOPTERS MEXICO QUERETARO     1   RP00165
7             ANA BARBARA CRUZ PALACIOS     3    TP0001
8                    FIDEICOMISO F/1596     1  TUE00207
9                    FIDEICOMISO F/1596     1  TUE00207
10                   FIDEICOMISO F/1596     1  TUE00207

                                       DESCR  PRECIO_UNITARIO  COSTO_UNITARIO  \
3       TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT           140.00           38.96
4    BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41          101.71
5      BAN P INOX 55MMX235MM 450W 127V T/TOR           237.07           49.41
6          REPARACION DE BATIDOR 16.6KW 440V         14000.00         5323.76
7       TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT            94.50           38.96
8   TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89
9   TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89
10  TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89

    COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  COSTO_TOTAL_CALCULADO  \
3                      38.96            140.00                  38.96
4                     101.71            344.83                 203.42
5                      49.41            474.14                  98.82
6                    5323.76          14000.00                5323.76
7                      38.96            283.50                 116.88
8                     517.89           1615.00                 517.89
9                     517.89           1615.00                 517.89
10                    517.89           1615.00                 517.89

    MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
3                      101.04                  101.04
4                       70.71                  141.41
5                      187.66                  375.32
6                     8676.24                 8676.24
7                       55.54                  166.62
8                     1097.11                 1097.11
9                     1097.11                 1097.11
10                    1097.11                 1097.11
  CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE  \
1  F37036 2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
4  F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
7  F37046 2022-01-05  LETICIA RAMIREZ HERNANDEZ     ANA BARBARA CRUZ PALACIOS

   CANT   CVE_ART                                    DESCR  PRECIO_UNITARIO  \
1     1  TUA00028  TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT          1264.05
4     2   BP00242  BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41
7     3    TP0001     TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT            94.50

   COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
1          327.18                    327.18           1264.05
4          101.71                    101.71            344.83
7           38.96                     38.96            283.50

   COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
1                 327.18                     936.87                  936.87
4                 203.42                      70.71                  141.41
7                 116.88                      55.54                  166.62

In [28]:
# 3.- Filtros por columnas
# filtro_columnas1: Muestra la columna 1 y 3 pero todas las filas
filtro_columnas1 = df.iloc[:, 1:3]
filtro_columnas1.to_csv("filtro_columnas1.csv", index=False)
print(filtro_columnas1)

# filtro_columnas2: Muestra las columnas 1, 4 y 5 pero todas las filas
filtro_columnas2 = df.iloc[:, [1, 4, 5]]
filtro_columnas2.to_csv("filtro_columnas2.csv", index=False)
print(filtro_columnas2)

      FECHA_DOC            NOMBRE_VENDEDOR
0    2022-01-05  LETICIA RAMIREZ HERNANDEZ
1    2022-01-05  LETICIA RAMIREZ HERNANDEZ
2    2022-01-05   DIEGO ARMANDO LEON DURAN
3    2022-01-05   DIEGO ARMANDO LEON DURAN
4    2022-01-05  LETICIA RAMIREZ HERNANDEZ
...         ...                        ...
1421 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425 2022-12-23         AARON NUÑO CORDOVA

[1426 rows x 2 columns]
      FECHA_DOC  CANT       CVE_ART
0    2022-01-05     1      TUE00244
1    2022-01-05     1      TUA00028
2    2022-01-05     7        TP0007
3    2022-01-05     1        TP0001
4    2022-01-05     2       BP00242
...         ...   ...           ...
1421 2022-12-23     6  CS12F1040A00
1422 2022-12-23     6  CS12H1050A00
1423 2022-12-23     3      TUE00394
1424 2022-12-23     1      TUA00470
1425 2022-12-23    10       RB00007

[1426 rows x 3 columns]

In [8]:
# Leer el archivo con una columna específica como índice
df1 = pd.read_excel('Detalle precios y productos fabricados 2022.xlsx', index_col=1)  # Si no se tiene un índice, Python genera uno automáticamente
print(df1.head())  # Mostrar las primeras filas con el nuevo índice

           CVE_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE  \
FECHA_DOC
2022-01-05  F37034  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
2022-01-05  F37036  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
2022-01-05  F37041   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS
2022-01-05  F37042   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ
2022-01-05  F37043  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL

            CANT   CVE_ART                                    DESCR  \
FECHA_DOC
2022-01-05     1  TUE00244  TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V
2022-01-05     1  TUA00028  TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT
2022-01-05     7    TP0007     TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT
2022-01-05     1    TP0001     TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT
2022-01-05     2   BP00242  BAN P INOX 115MMX235MM 1000W 127V T/TOR

            PRECIO_UNITARIO  COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  \
FECHA_DOC
2022-01-05           434.48           52.80                     52.80
2022-01-05          1264.05          327.18                    327.18
2022-01-05           551.61          177.68                    177.68
2022-01-05           140.00           38.96                     38.96
2022-01-05           172.41          101.71                    101.71

            SUBTOTAL_PARTIDA  COSTO_TOTAL_CALCULADO  \
FECHA_DOC
2022-01-05            434.48                  52.80
2022-01-05           1264.05                 327.18
2022-01-05           3861.29                1243.73
2022-01-05            140.00                  38.96
2022-01-05            344.83                 203.42

            MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
FECHA_DOC
2022-01-05                     381.68                  381.68
2022-01-05                     936.87                  936.87
2022-01-05                     373.94                 2617.56
2022-01-05                     101.04                  101.04
2022-01-05                      70.71                  141.41

In [29]:
# 4.-Filas vs columnas: Filtrar por clientes específicos y una columna relevante
filtro_filas_columnas = df[df["NOMBRE_CLIENTE"] == "PÚBLICO EN GENERAL"]["PRECIO_UNITARIO"]
filtro_filas_columnas.to_csv("filtro_filas_columnas.csv", index=False)
print(filtro_filas_columnas)

0        434.48
4        172.41
5        237.07
57       605.00
69       522.00
         ...
1371     576.65
1375     689.63
1376    3416.00
1392     410.00
1410     732.00
Name: PRECIO_UNITARIO, Length: 94, dtype: float64

In [30]:
# 5.-Filtro general: Mostrar las primeras filas del DataFrame
filtro_general = df.head()
filtro_general.to_csv("filtro_general.csv", index=False)
print(filtro_general)

  CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR                NOMBRE_CLIENTE  \
0  F37034 2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL
1  F37036 2022-01-05  LETICIA RAMIREZ HERNANDEZ  JUAN ANTONIO RESENDIZ UGALDE
2  F37041 2022-01-05   DIEGO ARMANDO LEON DURAN     ANA BARBARA CRUZ PALACIOS
3  F37042 2022-01-05   DIEGO ARMANDO LEON DURAN          OMAR RODRIGUEZ GOMEZ
4  F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ            PÚBLICO EN GENERAL

   CANT   CVE_ART                                    DESCR  PRECIO_UNITARIO  \
0     1  TUE00244  TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V           434.48
1     1  TUA00028  TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT          1264.05
2     7    TP0007     TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT           551.61
3     1    TP0001     TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT           140.00
4     2   BP00242  BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41

   COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
0           52.80                     52.80            434.48
1          327.18                    327.18           1264.05
2          177.68                    177.68           3861.29
3           38.96                     38.96            140.00
4          101.71                    101.71            344.83

   COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
0                  52.80                     381.68                  381.68
1                 327.18                     936.87                  936.87
2                1243.73                     373.94                 2617.56
3                  38.96                     101.04                  101.04
4                 203.42                      70.71                  141.41

In [31]:
# 6.-Filtro de las últimas filas del DataFrame
filtro_final = df.tail()
filtro_final.to_csv("filtro_final.csv", index=False)
print(filtro_final)

     CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR             NOMBRE_CLIENTE  \
1421  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ  LUIS ENRIQUE PATIÑO PEREZ
1422  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ  LUIS ENRIQUE PATIÑO PEREZ
1423  F39835 2022-12-23  LETICIA RAMIREZ HERNANDEZ       SEVEN DAYS ALL SPORT
1424  F39837 2022-12-23  LETICIA RAMIREZ HERNANDEZ        REVUELTA MONTECARLO
1425  F39838 2022-12-23         AARON NUÑO CORDOVA             CPEG SOLUTIONS

      CANT       CVE_ART                                     DESCR  \
1421     6  CS12F1040A00      CAS INOX 1/2"ØX3" 400W 127V EXT.30CM
1422     6  CS12H1050A00       CAS INOX 1/2"ØX4" 500W 127V EXT30CM
1423     3      TUE00394  TUB INOX 5/16"ØX300MM 5300W 220V "M" ESP
1424     1      TUA00470  TUB INOX 1/2"ØX500MM 10KW 220V 2 1/2"NPT
1425    10       RB00007   FAB  BOBINA DSD1 6 COLOCAR B/NUEVA 488V

      PRECIO_UNITARIO  COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  \
1421           712.00          102.31                    102.31
1422           718.60          104.69                    104.69
1423          2182.35            0.00                    596.55
1424          5909.84         1884.35                   1884.35
1425          1406.00            0.00                     80.66

      SUBTOTAL_PARTIDA  COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  \
1421           4272.00                 613.88                     609.69
1422           4311.60                 628.12                     613.91
1423           6547.05                1789.64                    1585.80
1424           5909.84                1884.35                    4025.49
1425          14060.00                 806.55                    1325.34

      MARGEN_TOTAL_CALCULADO
1421                 3658.12
1422                 3683.48
1423                 4757.41
1424                 4025.49
1425                13253.45

*Filtros basicos para variables cuantitativas*

In [32]:
# 7.-Filtros de comparación: Filtrar registros donde PRECIO_UNITARIO sea mayor a 7000
filtro_comparacion = df[df["PRECIO_UNITARIO"] > 10000]
filtro_comparacion.to_csv("filtro_comparacion.csv")
print(filtro_comparacion)

     CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR  \
6     F37044 2022-01-05   DIEGO ARMANDO LEON DURAN
40    F37102 2022-01-12             ALFREDO CANELA
347   F37697 2022-03-23   DIEGO ARMANDO LEON DURAN
373   F37734 2022-03-28   DIEGO ARMANDO LEON DURAN
419   F37817 2022-03-31             ALFREDO CANELA
479   F37933 2022-04-20  LETICIA RAMIREZ HERNANDEZ
558   F38097 2022-05-06             ALFREDO CANELA
588   F38160 2022-05-13             ALFREDO CANELA
655   F38315 2022-06-06         AARON NUÑO CORDOVA
672   F38352 2022-06-10             ALFREDO CANELA
842   F38648 2022-07-22  LETICIA RAMIREZ HERNANDEZ
851   F38665 2022-07-26   DIEGO ARMANDO LEON DURAN
866   F38705 2022-07-29             ALFREDO CANELA
931   F38850 2022-08-18  LETICIA RAMIREZ HERNANDEZ
960   F38910 2022-08-25             ALFREDO CANELA
1046  F39088 2022-09-20  LETICIA RAMIREZ HERNANDEZ
1101  F39191 2022-09-30  LETICIA RAMIREZ HERNANDEZ
1104  F39201 2022-09-30             ALFREDO CANELA
1226  F39436 2022-10-28             ALFREDO CANELA
1253  F39503 2022-11-04             ALFREDO CANELA
1277  F39560 2022-11-11             ALFREDO CANELA
1288  F39576 2022-11-15             ALFREDO CANELA
1296  F39592 2022-11-16   DIEGO ARMANDO LEON DURAN
1355  F39696 2022-12-05             ALFREDO CANELA
1360  F39716 2022-12-07             ALFREDO CANELA
1393  F39788 2022-12-19             ALFREDO CANELA
1412  F39824 2022-12-23             ALFREDO CANELA

                                         NOMBRE_CLIENTE  CANT    CVE_ART  \
6                   AIRBUS HELICOPTERS MEXICO QUERETARO     1    RP00165
40                                              DEACERO     3   TUE00321
347                 AIRBUS HELICOPTERS MEXICO QUERETARO     1    RP00165
373                                   DIECASTING CELAYA     2    BO00005
419          FABRICACION Y MONTAJE DE EQUIPO INDUSTRIAL     1   GAB00014
479                         JUAN CARLOS HERNANDEZ PEREZ     1   TUE00172
558                               PAS APPLIANCE SYSTEMS     2    EE00021
588                                               COLEP     1    RP00196
655                                           MEGO AFEK     1   TUA00325
672                                  FLEX-N-GATE MEXICO     1    RP00203
842                         JUAN CARLOS HERNANDEZ PEREZ     1   TUE00172
851                 AIRBUS HELICOPTERS MEXICO QUERETARO     1    RP00165
866                                 KERN LIEBERS MEXICO     1    EE00063
931                         JUAN CARLOS HERNANDEZ PEREZ     1   TUE00172
960                                            RICHALUM     2  BOBINA004
1046                             EDGAR GARCIA HERNANDEZ     1   TUE00378
1101                               CAROLINA PEREZ GOMEZ     2   TUE00382
1104                                KERN LIEBERS MEXICO     4    EE00063
1226                                KERN LIEBERS MEXICO     4    EE00063
1253  CENTRO DE INVESTIGACION Y DESARROLLO TECNOLOGI...     1    RP00192
1277                                          MEGO AFEK     2   TUA00325
1288                   CARCOUSTICS INDUSTRIAL DE MEXICO     1    EE00022
1296                AIRBUS HELICOPTERS MEXICO QUERETARO     1    RP00165
1355                                      SIKA MEXICANA     1    RP00229
1360                                  DIECASTING CELAYA     1    BO00005
1393                     WHITEHALL INDUSTRIES DE MEXICO     1   TUA00494
1412                                          MEGO AFEK     1   TUA00325

                                         DESCR  PRECIO_UNITARIO  \
6            REPARACION DE BATIDOR 16.6KW 440V         14000.00
40     TUB INOX 1/2"ØX1030MMX980MM 3KW480V "L"         12720.00
347          REPARACION DE BATIDOR 16.6KW 440V         14000.00
373      BO ABIERTA ALAMBRE CAL. 6 40 KW 440 V         18500.00
419   GABINETE ELECTRICO DE 50X40X20 70KW 440V         20887.18
479    TUB INOX 1/2"ØX670MM 22.5W480V BRIDA 6"         23995.24
558    FABRICACION DE CRISOL 500W 127V 50-60HZ         13800.00
588        REPARACION EQUIPO COCINA 5000W 22OV         13776.88
655   TUB INOX 1/2"ØX75CM "U" 30KW440V BRIDA6"         12500.00
672           REPARACION HORNO 15KW 440V TOTAL         32582.18
842    TUB INOX 1/2"ØX670MM 22.5W480V BRIDA 6"         25258.15
851          REPARACION DE BATIDOR 16.6KW 440V         14000.00
866            FABRICACIÓN ESPECIAL 1300W 115V         18869.00
931    TUB INOX 1/2"ØX670MM 22.5W480V BRIDA 6"         25258.15
960   RESIST TIPO BOBINA CAL. 6 DSD 30 KW 440V         18482.78
1046  TUB INOX 1/2"ØX746MM 30KW 440V "U" BRI8"         22417.60
1101    TUB INOX 1/2"ØX80CM 80KW 440V "U" PLAC         17393.06
1104           FABRICACIÓN ESPECIAL 1300W 115V         18869.00
1226           FABRICACIÓN ESPECIAL 1300W 115V         18869.00
1253       REPARACION DE HORNO LINDBERG/BLUE M         17450.00
1277  TUB INOX 1/2"ØX75CM "U" 30KW440V BRIDA6"         12500.00
1288       PLACAS DE FIBRA CERAMICA BARRENADAS         27808.00
1296         REPARACION DE BATIDOR 16.6KW 440V         14000.00
1355            REPARACION DE HORNO 1500W 127V         13688.00
1360     BO ABIERTA ALAMBRE CAL. 6 40 KW 440 V         18482.78
1393       TUB INOX 7/16"ØX105CM 24KW 480V 3PZ         11809.98
1412  TUB INOX 1/2"ØX75CM "U" 30KW440V BRIDA6"         12500.00

      COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
6            5323.76                   5323.76          14000.00
40              0.00                   1509.14          38160.00
347          5211.65                   5211.65          14000.00
373             0.00                   1560.44          37000.00
419             0.00                   1516.24          20887.18
479          4045.07                   4045.07          23995.24
558          2227.85                   2227.85          27600.00
588             0.00                   5301.49          13776.88
655          3900.52                   3900.52          12500.00
672             0.00                 199335.56          32582.18
842          5169.85                   5169.85          25258.15
851             0.00                    277.50          14000.00
866             0.00                   1721.28          18869.00
931          2754.67                   2754.67          25258.15
960          2613.60                   2613.60          36965.56
1046            0.00                   9353.62          22417.60
1101            0.00                   6073.50          34786.12
1104            0.00                   1721.28          75476.00
1226         1721.28                   1721.28          75476.00
1253            0.20                      0.20          17450.00
1277            0.00                   4604.19          25000.00
1288            0.00                    654.34          27808.00
1296            0.00                    277.50          14000.00
1355            0.00                      0.00          13688.00
1360         1734.88                   1734.88          18482.78
1393            0.00                   2335.20          11809.98
1412         4579.08                   4579.08          12500.00

      COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
6                   5323.76                    8676.24                 8676.24
40                  4527.42                   11210.86                33632.58
347                 5211.65                    8788.35                 8788.35
373                 3120.88                   16939.56                33879.12
419                 1516.24                   19370.94                19370.94
479                 4045.07                   19950.17                19950.17
558                 4455.70                   11572.15                23144.30
588                 5301.49                    8475.39                 8475.39
655                 3900.52                    8599.48                 8599.48
672               199335.56                 -166753.38              -166753.38
842                 5169.85                   20088.30                20088.30
851                  277.50                   13722.50                13722.50
866                 1721.28                   17147.72                17147.72
931                 2754.67                   22503.48                22503.48
960                 5227.20                   15869.18                31738.36
1046                9353.62                   13063.98                13063.98
1101               12146.99                   11319.56                22639.13
1104                6885.12                   17147.72                68590.88
1226                6885.12                   17147.72                68590.88
1253                   0.20                   17449.80                17449.80
1277                9208.38                    7895.81                15791.62
1288                 654.34                   27153.66                27153.66
1296                 277.50                   13722.50                13722.50
1355                   0.00                   13688.00                13688.00
1360                1734.88                   16747.90                16747.90
1393                2335.20                    9474.78                 9474.78
1412                4579.08                    7920.92                 7920.92

*Filtros basicos con conectores logicos*

In [22]:
# 8.-Filtros con condiciones múltiples (AND)
filtro_y = df[(df["PRECIO_UNITARIO"] < 6000) & (df["FECHA_DOC"] == "2022-01-05")]
filtro_y.to_csv("filtro_y.csv", index=False)
print(filtro_y)

   CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR  \
0   F37034 2022-01-05  LETICIA RAMIREZ HERNANDEZ
1   F37036 2022-01-05  LETICIA RAMIREZ HERNANDEZ
2   F37041 2022-01-05   DIEGO ARMANDO LEON DURAN
3   F37042 2022-01-05   DIEGO ARMANDO LEON DURAN
4   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
5   F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
7   F37046 2022-01-05  LETICIA RAMIREZ HERNANDEZ
8   F37048 2022-01-05   DIEGO ARMANDO LEON DURAN
9   F37049 2022-01-05   DIEGO ARMANDO LEON DURAN
10  F37050 2022-01-05   DIEGO ARMANDO LEON DURAN
11  F37051 2022-01-05   DIEGO ARMANDO LEON DURAN
12  F37052 2022-01-05   DIEGO ARMANDO LEON DURAN
13  F37053 2022-01-05   DIEGO ARMANDO LEON DURAN
14  F37054 2022-01-05   DIEGO ARMANDO LEON DURAN
15  F37058 2022-01-05   DIEGO ARMANDO LEON DURAN
16  F37059 2022-01-05   DIEGO ARMANDO LEON DURAN
17  F37060 2022-01-05   DIEGO ARMANDO LEON DURAN
18  F37061 2022-01-05             ALFREDO CANELA
19  F37061 2022-01-05             ALFREDO CANELA
20  F37061 2022-01-05             ALFREDO CANELA

                  NOMBRE_CLIENTE  CANT       CVE_ART  \
0             PÚBLICO EN GENERAL     1      TUE00244
1   JUAN ANTONIO RESENDIZ UGALDE     1      TUA00028
2      ANA BARBARA CRUZ PALACIOS     7        TP0007
3           OMAR RODRIGUEZ GOMEZ     1        TP0001
4             PÚBLICO EN GENERAL     2       BP00242
5             PÚBLICO EN GENERAL     2       BP00243
7      ANA BARBARA CRUZ PALACIOS     3        TP0001
8             FIDEICOMISO F/1596     1      TUE00207
9             FIDEICOMISO F/1596     1      TUE00207
10            FIDEICOMISO F/1596     1      TUE00207
11            FIDEICOMISO F/1596     1      TUE00207
12            FIDEICOMISO F/1596     1      TUE00207
13     SANDIBEEL BECERRA HURTADO     1       BO00051
14               INDUSTRIAS NIBA     1       BC00023
15            MOLINERA DE MEXICO     5       PT00070
16      SILCA CERAMICO PRODUCTOS     2        TP0011
17       OSCAR VALDEZ GUADARRAMA     3  PJ31C1F1AA00
18                      ELICAMEX     5      WRE-2133
19                      ELICAMEX     7      WRE-2774
20                      ELICAMEX     3      WRE-4885

                                       DESCR  PRECIO_UNITARIO  COSTO_UNITARIO  \
0    TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V           434.48           52.80
1    TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT          1264.05          327.18
2       TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT           551.61          177.68
3       TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT           140.00           38.96
4    BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41          101.71
5      BAN P INOX 55MMX235MM 450W 127V T/TOR           237.07           49.41
7       TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT            94.50           38.96
8   TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89
9   TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89
10  TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00          517.89
11  TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00            0.00
12  TUB INCOLOY 1/2"Øx412mm J 9KW 240V PLACA          1615.00            0.00
13  BOB 8020 CAL.26 127V BAS28.5CMX27CM MICA          1485.25            0.00
14   BC INOX 114MMØX165MM 1500W 230V C/ALLEN          2095.25            0.00
15  PT-100 1/8"ØX30MM EXT 1.5MT 3HILOS Z/ESP           192.50           51.73
16    TERMOPAR CERAMICO T/K" LONG 12" CAL 8"           771.28          124.00
17      TER J 3/16"ØX2" EXT.2MT CON-1/2" NPT           125.00            0.00
18  BAN MICA 120mmØx50mm 850W 440V TTORNILLO           821.30            0.00
19   BAN MICA Ø120MM X 50 MM 700W 440V T TOR           821.30            0.00
20     BAN INOX 36MMØX25MM 150W 240V EXT30CM           496.35           27.43

    COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  COSTO_TOTAL_CALCULADO  \
0                      52.80            434.48                  52.80
1                     327.18           1264.05                 327.18
2                     177.68           3861.29                1243.73
3                      38.96            140.00                  38.96
4                     101.71            344.83                 203.42
5                      49.41            474.14                  98.82
7                      38.96            283.50                 116.88
8                     517.89           1615.00                 517.89
9                     517.89           1615.00                 517.89
10                    517.89           1615.00                 517.89
11                    586.32           1615.00                 586.32
12                    586.32           1615.00                 586.32
13                     86.22           1485.25                  86.22
14                    742.05           2095.25                 742.05
15                    149.60            481.25                 397.08
16                    124.00           1542.56                 248.00
17                    141.90            375.00                 425.69
18                     78.70           4106.50                 393.48
19                     75.77           5749.10                 530.41
20                     27.43           1489.05                  82.29

    MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
0                      381.68                  381.68
1                      936.87                  936.87
2                      373.94                 2617.56
3                      101.04                  101.04
4                       70.71                  141.41
5                      187.66                  375.32
7                       55.54                  166.62
8                     1097.11                 1097.11
9                     1097.11                 1097.11
10                    1097.11                 1097.11
11                    1028.68                 1028.68
12                    1028.68                 1028.68
13                    1399.03                 1399.03
14                    1353.20                 1353.20
15                      42.90                   84.17
16                     647.28                 1294.56
17                     -16.90                  -50.69
18                     742.60                 3713.02
19                     745.53                 5218.69
20                     468.92                 1406.76

In [33]:
# 9.-Filtros con condiciones múltiples (OR)
filtro_o = df[(df["PRECIO_UNITARIO"] < 6000) | (df["FECHA_DOC"] == "2023-03-14")]
filtro_o.to_csv("filtro_o.csv", index=False)
print(filtro_o)

     CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR  \
0     F37034 2022-01-05  LETICIA RAMIREZ HERNANDEZ
1     F37036 2022-01-05  LETICIA RAMIREZ HERNANDEZ
2     F37041 2022-01-05   DIEGO ARMANDO LEON DURAN
3     F37042 2022-01-05   DIEGO ARMANDO LEON DURAN
4     F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
...      ...        ...                        ...
1421  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423  F39835 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424  F39837 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425  F39838 2022-12-23         AARON NUÑO CORDOVA

                    NOMBRE_CLIENTE  CANT       CVE_ART  \
0               PÚBLICO EN GENERAL     1      TUE00244
1     JUAN ANTONIO RESENDIZ UGALDE     1      TUA00028
2        ANA BARBARA CRUZ PALACIOS     7        TP0007
3             OMAR RODRIGUEZ GOMEZ     1        TP0001
4               PÚBLICO EN GENERAL     2       BP00242
...                            ...   ...           ...
1421     LUIS ENRIQUE PATIÑO PEREZ     6  CS12F1040A00
1422     LUIS ENRIQUE PATIÑO PEREZ     6  CS12H1050A00
1423          SEVEN DAYS ALL SPORT     3      TUE00394
1424           REVUELTA MONTECARLO     1      TUA00470
1425                CPEG SOLUTIONS    10       RB00007

                                         DESCR  PRECIO_UNITARIO  \
0      TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V           434.48
1      TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT          1264.05
2         TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT           551.61
3         TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT           140.00
4      BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41
...                                        ...              ...
1421      CAS INOX 1/2"ØX3" 400W 127V EXT.30CM           712.00
1422       CAS INOX 1/2"ØX4" 500W 127V EXT30CM           718.60
1423  TUB INOX 5/16"ØX300MM 5300W 220V "M" ESP          2182.35
1424  TUB INOX 1/2"ØX500MM 10KW 220V 2 1/2"NPT          5909.84
1425   FAB  BOBINA DSD1 6 COLOCAR B/NUEVA 488V          1406.00

      COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
0              52.80                     52.80            434.48
1             327.18                    327.18           1264.05
2             177.68                    177.68           3861.29
3              38.96                     38.96            140.00
4             101.71                    101.71            344.83
...              ...                       ...               ...
1421          102.31                    102.31           4272.00
1422          104.69                    104.69           4311.60
1423            0.00                    596.55           6547.05
1424         1884.35                   1884.35           5909.84
1425            0.00                     80.66          14060.00

      COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
0                     52.80                     381.68                  381.68
1                    327.18                     936.87                  936.87
2                   1243.73                     373.94                 2617.56
3                     38.96                     101.04                  101.04
4                    203.42                      70.71                  141.41
...                     ...                        ...                     ...
1421                 613.88                     609.69                 3658.12
1422                 628.12                     613.91                 3683.48
1423                1789.64                    1585.80                 4757.41
1424                1884.35                    4025.49                 4025.49
1425                 806.55                    1325.34                13253.45

[1381 rows x 14 columns]

In [34]:
# 10.-Filtros de exclusión: Excluir registros con una fecha específica
filtro_exclusion = df[~(df["FECHA_DOC"] == "2023-03-14")]
filtro_exclusion.to_csv("filtro_exclusion.csv", index=False)
print(filtro_exclusion)

     CVE_DOC  FECHA_DOC            NOMBRE_VENDEDOR  \
0     F37034 2022-01-05  LETICIA RAMIREZ HERNANDEZ
1     F37036 2022-01-05  LETICIA RAMIREZ HERNANDEZ
2     F37041 2022-01-05   DIEGO ARMANDO LEON DURAN
3     F37042 2022-01-05   DIEGO ARMANDO LEON DURAN
4     F37043 2022-01-05  LETICIA RAMIREZ HERNANDEZ
...      ...        ...                        ...
1421  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1422  F39834 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1423  F39835 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1424  F39837 2022-12-23  LETICIA RAMIREZ HERNANDEZ
1425  F39838 2022-12-23         AARON NUÑO CORDOVA

                    NOMBRE_CLIENTE  CANT       CVE_ART  \
0               PÚBLICO EN GENERAL     1      TUE00244
1     JUAN ANTONIO RESENDIZ UGALDE     1      TUA00028
2        ANA BARBARA CRUZ PALACIOS     7        TP0007
3             OMAR RODRIGUEZ GOMEZ     1        TP0001
4               PÚBLICO EN GENERAL     2       BP00242
...                            ...   ...           ...
1421     LUIS ENRIQUE PATIÑO PEREZ     6  CS12F1040A00
1422     LUIS ENRIQUE PATIÑO PEREZ     6  CS12H1050A00
1423          SEVEN DAYS ALL SPORT     3      TUE00394
1424           REVUELTA MONTECARLO     1      TUA00470
1425                CPEG SOLUTIONS    10       RB00007

                                         DESCR  PRECIO_UNITARIO  \
0      TUB COBRE 5/16"ØX165MM CIRCULA1.5KW127V           434.48
1      TUA U" 5/16 ØX250MM 1200W 120V TAP1"NPT          1264.05
2         TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 7 MT           551.61
3         TERMOPAR J 3/16 Ø X 1' 1/2 EXT. 1 MT           140.00
4      BAN P INOX 115MMX235MM 1000W 127V T/TOR           172.41
...                                        ...              ...
1421      CAS INOX 1/2"ØX3" 400W 127V EXT.30CM           712.00
1422       CAS INOX 1/2"ØX4" 500W 127V EXT30CM           718.60
1423  TUB INOX 5/16"ØX300MM 5300W 220V "M" ESP          2182.35
1424  TUB INOX 1/2"ØX500MM 10KW 220V 2 1/2"NPT          5909.84
1425   FAB  BOBINA DSD1 6 COLOCAR B/NUEVA 488V          1406.00

      COSTO_UNITARIO  COSTO_UNITARIO_CALCULADO  SUBTOTAL_PARTIDA  \
0              52.80                     52.80            434.48
1             327.18                    327.18           1264.05
2             177.68                    177.68           3861.29
3              38.96                     38.96            140.00
4             101.71                    101.71            344.83
...              ...                       ...               ...
1421          102.31                    102.31           4272.00
1422          104.69                    104.69           4311.60
1423            0.00                    596.55           6547.05
1424         1884.35                   1884.35           5909.84
1425            0.00                     80.66          14060.00

      COSTO_TOTAL_CALCULADO  MARGEN_UNITARIO_CALCULADO  MARGEN_TOTAL_CALCULADO
0                     52.80                     381.68                  381.68
1                    327.18                     936.87                  936.87
2                   1243.73                     373.94                 2617.56
3                     38.96                     101.04                  101.04
4                    203.42                      70.71                  141.41
...                     ...                        ...                     ...
1421                 613.88                     609.69                 3658.12
1422                 628.12                     613.91                 3683.48
1423                1789.64                    1585.80                 4757.41
1424                1884.35                    4025.49                 4025.49
1425                 806.55                    1325.34                13253.45

[1426 rows x 14 columns]

In [35]:
# Guardar los DataFrames en nuevos archivos si es necesario
df.to_csv("detalle_productos_procesado.csv")